"""Tablas iniciales

Revision ID: 1ab80ec632b2
Revises: 
Create Date: 2026-02-04 23:06:27.693603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab80ec632b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('stand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('carrera', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('bloque_id', sa.Integer(), nullable=True),
    sa.Column('tiene_regalo', sa.Boolean(), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.Column('token_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['bloque_id'], ['bloque.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_uuid')
    )
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estudiante_rut'), ['rut'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('stand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stand_id'], ['stand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('encuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('evaluacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('stand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['stand_id'], ['stand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_id', 'stand_id', name='una_visita_por_stand')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visita')
    op.drop_table('encuesta')
    op.drop_table('user')
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estudiante_rut'))

    op.drop_table('estudiante')
    op.drop_table('stand')
    op.drop_table('configuracion')
    op.drop_table('bloque')
    # ### end Alembic commands ###
