"""Probando indices y hora localmente

Revision ID: 325be73b8f3d
Revises: 1ab80ec632b2
Create Date: 2026-02-10 20:23:05.769918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '325be73b8f3d'
down_revision = '1ab80ec632b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('visita', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index('idx_visita_estudiante', ['estudiante_id'], unique=False)
        batch_op.create_index('idx_visita_stand', ['stand_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visita', schema=None) as batch_op:
        batch_op.drop_index('idx_visita_stand')
        batch_op.drop_index('idx_visita_estudiante')
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
