"""Agregar creador y fecha de creacion a Estudiante

Revision ID: 4d66c4df69dc
Revises: 59216ccd1955
Create Date: 2026-03-06 15:54:21.817357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d66c4df69dc'
down_revision = '59216ccd1955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_por_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['creado_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('creado_por_id')

    # ### end Alembic commands ###
