"""Ampliar limites de rut, nombre_stand y config

Revision ID: 59216ccd1955
Revises: c1a799409207
Create Date: 2026-02-26 15:46:36.952962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59216ccd1955'
down_revision = 'c1a799409207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('stand', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stand', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
