"""Eliminar modelo Config, unificar logica y fix largo configuracion

Revision ID: c1a799409207
Revises: 325be73b8f3d
Create Date: 2026-02-10 22:33:57.093646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a799409207'
down_revision = '325be73b8f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.alter_column('carrera',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('carrera',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    op.create_table('config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('valor', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('config_pkey')),
    sa.UniqueConstraint('clave', name=op.f('config_clave_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
